[platformio]
default_envs = esp32-s3-devkitc-1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
build_flags =
  -std=gnu++17
lib_deps =
  bblanchon/ArduinoJson @ ^7.1.0
  adafruit/Adafruit SSD1306 @ ^2.5.11
  adafruit/Adafruit NeoPixel @ ^1.12.3

[env:esp32-c3-devkitm-1]
board = esp32-c3-devkitm-1
build_flags =
  ${env.build_flags}
  -DOPEN_PILL_TARGET_ESP32_C3

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
upload_port = COM10
monitor_port = COM10
build_flags =
  ${env.build_flags}
  -DOPEN_PILL_TARGET_ESP32_S3
